INSERT INTO blood_test_categories(id,
                                  name,
                                  aliases,
                                  description,
                                  speciality,
                                  unit,
                                  lower_range,
                                  upper_range)
VALUES (uuid(),
        "Glucose",
        "Blood sugar, Fasting blood sugar, Blood glucose",
        "Blood glucose tests are usually used to check for or monitor diabetes.",
        "Endocrinologist",
        "mmol/L",
        3.9,
        4.9),
    (uuid(),
     "HbA1c",
     "Haemoglobin A1c, Glycated, glycosylated haemoglobin",
     "The test for HbA1c shows how well your diabetes has been controlled over the last 2-3 months. Even though you may have some very high or very low blood glucose values, HbA1c will give a picture of the average level of glucose in your blood over that time period. The result can help you and your doctor understand if the measures you are taking to control your diabetes are working.",
     "Endocrinologist",
     "%",
     4.0,
     5.6);